language: cpp

sudo: required

dist: xenial

compiler:
    - gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install wget libxerces-c-dev xsdcxx -qq
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && pushd ${DEPS_DIR}
    - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6-Linux-x86_64.tar.gz
    - tar -xvf cmake-3.19.6-Linux-x86_64.tar.gz > /dev/null
    - export PATH="${DEPS_DIR}/cmake-3.19.6-Linux-x86_64/bin/:$PATH"
    - popd ${TRAVIS_BUILD_DIR}

script:
    - ls -alt
    - mkdir NeuroML_API_build
    - cd NeuroML_API_build
    - cmake ..
    - make
    - ctest
    - ./create_net network.nml
    - ./example network.nml
    - ls -alt
