language: cpp

sudo: required

dist: xenial

compiler:
    - gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq cmake libxerces-c-dev xsdcxx

script:
    - ls -alt
    - mkdir NeuroML_API_build
    - cd NeuroML_API_build
    - cmake ..
    - make
    - ctest
    - ./create_net network.nml
    - ./example network.nml
    - ls -alt
