language: cpp

sudo: required

dist: focal

compiler:
    - gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install wget libxerces-c-dev xsdcxx cmake -qq

script:
    - ls -alt
    - mkdir NeuroML_API_build
    - cd NeuroML_API_build
    - cmake -DREGENERATE_BINDINGS=ON ..
    - make
    - ctest
    - ./create_net network.nml
    - ./example network.nml
    - ls -alt
