name: Continuous builds

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt-get update -qq
        sudo apt-get install libxerces-c-dev xsdcxx cmake -qq

    - name: Create build folder for out-of-source build
      shell: bash
      run: |
        mkdir ${{github.workspace}}/NeuroML_API_build

    - name: Configure CMake build
      working-directory: ${{github.workspace}}/NeuroML_API_build
      shell: bash
      run: |
        cmake $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{github.workspace}}/NeuroML_API_build
      shell: bash
      run: |
        cmake --build .

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/NeuroML_API_build
      run: |
        ctest
        ./create_net network.nml
        ./example network.nml
        ls -alt
